/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.systemeexpert;

import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author elhou
 */
public class expertFrame extends javax.swing.JFrame {
    
    ArrayList<String> nouveauxRegles = new ArrayList<String>();
    
    Expert expert =new Expert();
    /**
     * Creates new form expertFrame
     */
    public expertFrame() {
        initComponents();
        afficherRegle();
    }

    public expertFrame(Expert e) {
        
        initComponents();
        expert =e;
        afficherRegle();
    }
    
    public void afficherRegle(){
        nouveauxRegles.clear();
        nouveauxRegles = MyConnection.nouveauRegles();
        
        if(nouveauxRegles.isEmpty()){
            newRegleLabel.setText("il n'y a aucune demande a ce moment");
            newFaitTextField.setEnabled(false);
            newFaitTextField.setEditable(false);
        }else{
            newRegleLabel.setText(nouveauxRegles.get(0));
        }
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        newRegleLabel = new javax.swing.JLabel();
        newFaitTextField = new javax.swing.JTextField();
        ValiderButton = new javax.swing.JButton();
        deconnecterButton = new javax.swing.JButton();
        SupprimerButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 255, 255));

        newFaitTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newFaitTextFieldActionPerformed(evt);
            }
        });

        ValiderButton.setText("Valider");
        ValiderButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ValiderButtonActionPerformed(evt);
            }
        });

        deconnecterButton.setText("Se deconnecter");
        deconnecterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deconnecterButtonActionPerformed(evt);
            }
        });

        SupprimerButton.setText("Supprimer");
        SupprimerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SupprimerButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(179, 179, 179)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(newFaitTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 418, Short.MAX_VALUE)
                    .addComponent(newRegleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(deconnecterButton)
                .addGap(30, 30, 30))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(228, 228, 228)
                .addComponent(ValiderButton, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(148, 148, 148)
                .addComponent(SupprimerButton)
                .addContainerGap(201, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(newRegleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(deconnecterButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(51, 51, 51)
                .addComponent(newFaitTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ValiderButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SupprimerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(93, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ValiderButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ValiderButtonActionPerformed
        String newFait = newFaitTextField.getText();
        if(newFait.isEmpty()){
            JOptionPane.showMessageDialog(null, "veuiller entrer le fait");
        }
        else{

            PreparedStatement ps = null;
            String query ="UPDATE `reglesfait` SET `Fait`= ? WHERE `Regles`=?";
            try {
                ps= MyConnection.getConnection().prepareStatement(query);

                
                ps.setString(1, newFait);
                ps.setString(2, newRegleLabel.getText().trim());
                

                if(ps.executeUpdate()>0){
                    JOptionPane.showMessageDialog(null, "Fait a eté ajouté avec succès");
                }
            } catch (SQLException ex) {
                System.out.println(ex);
                
            }finally {
            	try {
            		if(ps !=null && !ps.isClosed()) {
            			ps.close();
            		}
            	}catch (Exception e) {
            		System.out.println(e);
				}
            }
            
            expertFrame frame = new expertFrame(expert);
            frame.setVisible(true);
            this.dispose();
            
        }
        
        
    }//GEN-LAST:event_ValiderButtonActionPerformed

    private void newFaitTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newFaitTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newFaitTextFieldActionPerformed

    private void deconnecterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deconnecterButtonActionPerformed
        LoginFrame fram = new LoginFrame();
        fram.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_deconnecterButtonActionPerformed

    private void SupprimerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SupprimerButtonActionPerformed
            PreparedStatement ps;
            String query ="DELETE FROM `reglesfait` WHERE `Regles`=?";
            try {
                ps= MyConnection.getConnection().prepareStatement(query);
                
                ps.setString(1, newRegleLabel.getText().trim());
                

                if(ps.executeUpdate()>0){
                    JOptionPane.showMessageDialog(null, "Demande a ete supprimé");
                }
            } catch (SQLException ex) {
                System.out.println(ex);
                
            }
            
            expertFrame frame = new expertFrame(expert);
            frame.setVisible(true);
            this.dispose();
        
        
        
    }//GEN-LAST:event_SupprimerButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(expertFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(expertFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(expertFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(expertFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new expertFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton SupprimerButton;
    private javax.swing.JButton ValiderButton;
    private javax.swing.JButton deconnecterButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField newFaitTextField;
    private javax.swing.JLabel newRegleLabel;
    // End of variables declaration//GEN-END:variables
}
